version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: alz_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: alz 
      POSTGRES_PASSWORD: 123 
      POSTGRES_DB: alz_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: alz_postgres_data

